language: java

script:
  - cd aula-01/java && mvn test checkstyle:check spotbugs:check verify -P cobertura
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - openjdk8
  
